// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/cross-platform-apps": {
    params: {};
  };
  "/website-development": {
    params: {};
  };
  "/computer-repair": {
    params: {};
  };
  "/family-support": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/cross-platform-apps" | "/website-development" | "/computer-repair" | "/family-support" | "/contact";
  };
  "routes/cross-platform-apps.tsx": {
    id: "routes/cross-platform-apps";
    page: "/cross-platform-apps";
  };
  "routes/website-development.tsx": {
    id: "routes/website-development";
    page: "/website-development";
  };
  "routes/computer-repair.tsx": {
    id: "routes/computer-repair";
    page: "/computer-repair";
  };
  "routes/family-support.tsx": {
    id: "routes/family-support";
    page: "/family-support";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/cross-platform-apps": typeof import("./app/routes/cross-platform-apps.tsx");
  "routes/website-development": typeof import("./app/routes/website-development.tsx");
  "routes/computer-repair": typeof import("./app/routes/computer-repair.tsx");
  "routes/family-support": typeof import("./app/routes/family-support.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
};